INSERT INTO users (name, age) VALUES ("1", 1);
INSERT INTO users (name, age) VALUES ("2", 2);
INSERT INTO users (name, age) VALUES ("3", 3);
INSERT INTO users (name, age) VALUES ("4", 4);
INSERT INTO users (name, age) VALUES ("5", 5);
INSERT INTO users (name, age) VALUES ("6", 6);
INSERT INTO users (name, age) VALUES ("7", 7);
INSERT INTO users (name, age) VALUES ("8", 8);
INSERT INTO users (name, age) VALUES ("9", 9);
INSERT INTO users (name, age) VALUES ("10", 10);
INSERT INTO users (name, age) VALUES ("11", 11);
INSERT INTO users (name, age) VALUES ("12", 12);
INSERT INTO users (name, age) VALUES ("13", 13);
INSERT INTO users (name, age) VALUES ("14", 14);
INSERT INTO users (name, age) VALUES ("15", 15);
INSERT INTO users (name, age) VALUES ("16", 16);
INSERT INTO users (name, age) VALUES ("17", 17);
INSERT INTO users (name, age) VALUES ("18", 18);
INSERT INTO users (name, age) VALUES ("19", 19);
INSERT INTO users (name, age) VALUES ("20", 20);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("1", "1", 1, "1", "1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("2", "2", 2, "2", "2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("3", "3", 3, "3", "3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("4", "4", 4, "4", "4");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("5", "5", 5, "5", "5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("6", "6", 6, "6", "6");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("7", "7", 7, "7", "7");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("8", "8", 8, "8", "8");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("9", "9", 9, "9", "9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("10", "10", 10, "10", "10");

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (19, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (21, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (22, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (23, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (24, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (26, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (28, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (29, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 10, 10);