INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "CS", 1000, "5/27", "8/2");
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO users (name, age) VALUES ("Max", 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);