INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES(null, null, null, null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO users (id, name, age) VALUES(null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(null, null, null, null);

